FROM mcr.microsoft.com/devcontainers/base:ubuntu

WORKDIR /workspace

RUN apt-get update && \
    apt-get install -y \
    xz-utils \
    gcc \
    g++ \
    cmake \
    unzip \
    git \
    wget \
    python3.11 \
    python3-pip \
    dos2unix \
    libreadline-dev \
    libnsl-dev \
    libcurl4-openssl-dev \
    libperl-dev \
    perl-doc
